apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    orgId: 1
    version: 1
    editable: true
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    version: 1
    # Data links for seamless integration with logs and metrics if Loki/Prometheus are present
    ui:
      datasources:
        - name: Loki
          uid: loki
        - name: Prometheus
          uid: prometheus
