global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: rabbitmq
    honor_labels: true
    metrics_path: /metrics
    static_configs:
    - targets: ["rabbitmq:15692"]
  - job_name: 'postgres_multi'
    metrics_path: /probe
    static_configs:
      - targets:
          - "postgresql://postgres:example@postgres-database:5432/lostcities-accounts?sslmode=disable"
          - "postgresql://postgres:example@postgres-database:5432/lostcities-gamestate?sslmode=disable"
          - "postgresql://postgres:example@postgres-database:5432/lostcities-matches?sslmode=disable"
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187
  - job_name: accounts
    honor_labels: true
    metrics_path: /management/accounts/actuator/prometheus
    params:
      format: [ "prometheus" ]
    static_configs:
    - targets: [ "host.containers.internal:4450", ]
  - job_name: matches
    honor_labels: true
    metrics_path: /management/matches/actuator/prometheus
    params:
      format: [ "prometheus" ]
    static_configs:
      - targets: [ "host.containers.internal:4453", ]
  - job_name: gamestate
    honor_labels: true
    metrics_path: /management/gamestate/actuator/prometheus
    params:
      format: [ "prometheus" ]
    static_configs:
      - targets: [ "host.containers.internal:4454", ]
  - job_name: player-events
    honor_labels: true
    metrics_path: /management/player-events/actuator/prometheus
    params:
      format: [ "prometheus" ]
    static_configs:
      - targets: [ "host.containers.internal:4455", ]
